# Your project's server will run on proxy
PROXY: "https://local.jacmoe.dk"

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "themes/m/assets/dist"
  # Path to source folder
  src: "themes/m/assets/src"
  # Paths to fonts
  fonts:
    - "themes/m/assets/src/fonts/**/*"
    - "bower_components/font-awesome/fonts/**/*"
  # Paths to images
  images:
    - "themes/m/assets/src/img/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/font-awesome/scss"
    - "vendor/scrivo/highlight.php/styles"
